// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acukldizwystboilwdqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdWtsZGl6d3lzdGJvaWx3ZHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTAzMDksImV4cCI6MjA2NDY4NjMwOX0.ucdSb7U5dH7Jh3whDwF6CNU1JmGzv74neFFHeTVW2dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);